services:
  db:
    image: bitnami/postgresql
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=7562
      - POSTGRES_DB=sleekdb
    volumes:
      - polls_pg_data:/bitnami/postgresql

volumes:
  polls_pg_data: